name: Run Python Tests on altoro mutual repository
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          chromedriver-version: '80.0.3987.106'
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm ci
          npm run build
          npm test
          google-chrome --version
          sudo pip3 install selenium
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # disable headless mode
      # Execute Test for altoro mutual
      - name: Run test for altoro mutual
        run: python tests/test_altoro_mutual_form.py
