name: "Testing setup"
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    branches:
      - '*'
    paths:
      - '**'
      - '!*.md'
jobs:
  test_default_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        python-version: 3.8
    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
    - name: setup
      run: |
        google-chrome --version
        sudo pip3 install selenium
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # disable headless mode
        pip install -r requirements.txt
        python tests/test_altoro_mutual_form.py
